services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - ${LOCAL_SERVER_IP}:53:53/tcp
      - ${LOCAL_SERVER_IP}:53:53/udp
      - 8081:80/tcp
    environment:
      TZ: 'Europe/Copenhagen'
      FTLCONF_webserver_api_password: ${PIHOLE_WEBUI_PASSWORD}
    volumes:
      - ${PIHOLE_CONFIGURATION_LOCATION}:/etc/pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: private-nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ${NGINX_PROXY_MANAGER_CONFIGURATION_LOCATION}/data:/data
      - ${NGINX_PROXY_MANAGER_CONFIGURATION_LOCATION}/letsencrypt:/etc/letsencrypt