services:
  teamspeak:
    image: teamspeak:latest
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
      - 41144:41144
    env_file: "teamspeak.env"
    volumes:
      - ts3-volume:/var/ts3server/
    
  db:
    image: mariadb
    restart: always
    env_file: "database.env"
volumes:
  ts3-volume:
