services:
  vintage_story:
    image: neebz/vintage-story-server:2026.05.10-1-rc-2
    ports:
      - "42420:42420/tcp"
      - "42420:42420/udp"
    volumes:
      - ${GAME_FILES_LOCATION}:/app/data
      - vintage-story-cache:/app/cache
    environment:
      VERSION: ${VERSION}
      CHANNEL: ${CHANNEL}
    user: "1000:1000"  # This ensures the container uses the correct UID/GID
      
volumes:
  vintage-story-cache: