services:
  vintage_story:
    image: neebz/vintage-story-server:v1.20.3
    ports:
      - "42420:42420/tcp"
      - "42420:42420/udp"
    volumes:
      - ${GAME_FILES_LOCATION}:/app/data
      - vintage-story-files:/app/server  # Docker-managed named volume
    environment:
      VERSION: ${VERSION} 
    user: "1000:1000"  # This ensures the container uses the correct UID/GID
      
volumes:
  vintage-story-files: