services:
  vintage_story:
    image: neebz/vintage-story-server:2026.05.10-1-rc-8
    ports:
      - "42420:42420/tcp"
      - "42420:42420/udp"
    volumes:
      - ${GAME_FILES_LOCATION}:/app/data
      - vintage-story-files:/app/server  # Docker-managed named volume
    environment:
      VERSION: ${VERSION}
      CHANNEL: ${CHANNEL}
    user: 1000:1000
      
volumes:
  vintage-story-files: