networks:
    monitor-net:
        driver: bridge

services:
  prometheus:
    image: docker.io/prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - 9090:9090
    command: 
      - $"--config.file={CONFIG_FILE}"
    volumes:
      - ${VOLUME_LOCATION}:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - monitor-net
      
  grafana:
    image: grafana/grafana-enterprise
    container_name: 'grafana'
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitor-net

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc) ($$|/)'
    networks:
      - monitor-net
    pid: host
    ports:
      - 9100:9100
    expose:
      - 9100
    restart: unless-stopped
      
volumes:
  prometheus-data:
  grafana-storage:
    driver: local